### ISSUE TITLE
Source of the ‘’ellipsoid‘’ function

### ISSUE THREAD

**Issue by WGBmushi** [SafeRoboticsLab/Dual_Control_HRI#1]
A great job.

I encountered an error while testing the code that I would appreciate your assistance with. Specifically, I received the following message: "check for incorrect argument data type or missing argument in the call to function '**ellipsoid**'". Despite attempting to resolve the issue using the MPT3 toolbox and the MATLAB default 'ellipsoid' functions, neither approach succeeded.

If it's convenient for you, could you let me know where the 'ellipsoid' function you used came from?

Thanks again.

**Comment by HaiminClack** [comment]
It is from the [Ellipsoidal Toolbox (ET)](https://www.mathworks.com/matlabcentral/fileexchange/21936-ellipsoidal-toolbox-et).
